services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./:/app 
    depends_on:
      - db  

  db:
    image: postgres:13.1  
    container_name: db  
    environment:
      POSTGRES_USER: "postgres"  
      POSTGRES_PASSWORD: "postgres" 
      POSTGRES_DB: "dev"
    ports:
      - "5432:5432"  

    # ヘルスチェック (いらないかも)

    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U postgres"]  
    #   interval: 10s  
    #   timeout: 5s  
    #   retries: 10  
